version: '2.0'
services:
  sanic_board:
    container_name: sanic_board
    environment:
      - SERVICE_NAME=sanic_board
    build:
      context: .
      dockerfile: /Dockerfile
    image: "sanic_board"
    depends_on:
      - "postgres"
    restart: unless-stopped
    ports:
      - "8000"
    networks:
      - default
  postgres:
    container_name: postgres
    environment:
      - SERVICE_NAME=postgres
      - POSTGRES_PASSWORD=docker
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - /etc/postgresql
      - /var/log/postgresql
      - /var/lib/postgresql
    image: "postgres"
    restart: unless-stopped
    ports:
      - "5432"
    networks:
      - default
